services:
  - type: web
    name: voice-emotion-analysis
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: FLASK_PORT
        value: "5000"
